SPOTIFY_CLIENT_ID = ''
SPOTIFY_CLIENT_SECRET = ''
SPOTIFY_REDIRECT_URI = ''
SPOTIFY_USER_NAME = ''

OPEN_WEATHER_MAP_API_KEY = ''
OPEN_WATHER_MAP_NUREMBERG_ID = -1

PATH_TO_DATA_REPO = ''

HOURS_FROM_UTC = 2
