SPOTIFY_CLIENT_ID = ''
SPOTIFY_CLIENT_SECRET = ''
SPOTIFY_REDIRECT_URI = ''
SPOTIFY_USER_NAME = ''

OPEN_WEATHER_MAP_API_KEY = ''
OPEN_WATHER_MAP_NUREMBERG_ID = 0

PATH_TO_DATA_REPO = ''
LAST_IMPORTED_DATETIME_FILE_PATH = ''
